### PR TITLE
chore: add 🏭 to README.md

### PR DESCRIPTION
**Pull request by Racer159**
## Description

This adds the 🏭 to the README.md per @oates instructions.

## Related Issue

Fixes #N/A

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Other (security config, docs update, etc)

## Checklist before merging

- [X] Test, docs, adr added or updated as needed
- [X] [Contributor Guide Steps](https://github.com/defenseunicorns/uds-package-mattermost/blob/main/CONTRIBUTING.md#developer-workflow) followed

### CODE REVIEW

**Review by oates — APPROVED** [review]
lgtm

**Review by mjnagel — COMMENTED** [review]
Current workflow rules don't trigger the required checks due to this PR only changing the readme. It's a problem we've had in the past too, on uds-core we just run all the checks always but there's probably a nicer solution where the jobs always execute but in their step logic consider filepaths change in how they execute (i.e. running tests vs not).

**Comment by mjnagel** [comment]
@Racer159 nice, yeah that makes sense to add and feels like a relatively clean solution.

**Comment by zachariahmiller** [comment]
Created https://github.com/defenseunicorns/uds-package-mattermost/issues/25 to track the work needed for this. Once implemented this PR will be able to be merged

**Pull request merged**
